# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: imdbbot
language: python
runtimeConfig:
  start:
    - 'fastapi run imdbbot/main.py'
database:
  hostname: localhost
  port: 5432
  username: postgres
  password: ${PGPASSWORD}
  app_db_name: imdbbot
  migrate:
    - alembic upgrade head
telemetry:
  logs:
    logLevel: DEBUG
env:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
  SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
